name: Update News

on:
  schedule:
    - cron: '0 9,18 * * *'  # Run at 9 AM and 6 PM UTC daily
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Create data directory
        run: |
          mkdir -p public/data
          echo "Created public/data directory"
          ls -la public/data
          
      - name: Install dependencies
        run: |
          npm ci
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
      
      - name: Fetch latest news
        run: |
          echo "Starting news fetch..."
          node scripts/fetchNews.js
          echo "News fetch complete"
          if [ -f "public/data/news.json" ]; then
            echo "Content of news.json:"
            cat public/data/news.json
          else
            echo "Error: news.json was not created"
            exit 1
          fi
        env:
          CRYPTO_PANIC_API_KEY: ${{ secrets.CRYPTO_PANIC_API_KEY }}
      
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: Commit and push if changes
        run: |
          echo "Checking for changes..."
          git add public/data/news.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            echo "Changes detected, committing..."
            git commit -m "Update news data [skip ci]"
            git push
            echo "Changes pushed successfully"
          fi 